### ISSUE TITLE
Crashed server when going on it

### ISSUE THREAD

**Issue by Darkmega18** [Seraphaestus/HistoricizedMedicine#17]
[crash-2018-07-01_05.42.00-server.txt](https://github.com/Seraphaestus/HistoricizedMedicine/files/2152694/crash-2018-07-01_05.42.00-server.txt)

It blew the server as I loaded into the world. don't think it blew up on the client tho, as i managed to get into a world for a brief moment to make sure it ran.

**Comment by Sunconure11** [comment]
Any other specific info you are able to give on this error? Seraph is dealing with some things so I'll try and debug his mod for him in the mean time.

**Comment by Darkmega18** [comment]
thats all I could discern. it was the first iteration of a modpack that stacks exploration, dungeons and RPG elements together I was meaning to call "Transcendence". No health regen, but has rally restoration, healing items, healer abilities and natural absorption shields for minor damage resisting. Was gonna have this for a bit more spice, but well, yeah, some rats are ticking as soon as I loaded into the server and it went down and had to restart itself. that was the log it spat. :V mod list would be in the log, so thats about it.

**Comment by Sunconure11** [comment]
I believe I've fixed it, but before I send out a pull request, I want to see if it's solved your problems. Run this build on both the server and client for testing purposes only. Try spawning in lots of rats.

https://www.dropbox.com/s/vdfr2isbwuqqrbd/historicizedmedicine-1.3.3.jar?dl=0

**Comment by Darkmega18** [comment]
it won't be tonight. but I can give it a whirl tomorrow after work. so it'll be about a day before I can get back to you. but i'll give it a shot and get back to you. thanks for giving it a shot. :)

**Comment by Sunconure11** [comment]
Any news on this?

**Comment by Darkmega18** [comment]
apologies. I used a different server last night due to testing minestuck mod with a friend and he didn't want to deal with my usual crap of having too many mods. so I didn't get to it. but I'll give it a shot in a bit when I give the server side of my pack a quick go.

**Comment by Darkmega18** [comment]
That seems to have done it. The bleeding particles being left on the ground and the endless slowness+weakness from pain is from yours, right? Cause I just got metroided by invisible brain slimes and had close to no health so had to report that issue, but noticed there was more blood splatters than zombie awareness was capable of. :V 
Also is bleeding nonlethal? cause it didn't seem to be killing me. unless I got lucky on half a heart.

**Comment by Sunconure11** [comment]
Not sure what you're referring to, but I'll send over the pull now.

**Comment by Darkmega18** [comment]
it was an issue to primitive mobs. but as a side effect of the damage I noticed blood particles dropping from me and having a slowness and weakness, which I think are two effects this mod has. Bleeding which ticks your health over time and then pain which the curse page says causes slowness and weakness.

then I asked if the bleeding can finish you off or if it's nonlethal like poison ticks. cause I had the blood particle drops but was on half a heart and didn't seem to be dieing from it. Although my absorption hearts had come back at that point.

**Comment by Darkmega18** [comment]
whoa crap, ok, it's blowing up again on the server all of a sudden, but no crash log once more. but it's different. something about a recipe json. (gonna just post some of the console stuff from the multicraft console. it's upside down due to how it displays the logs.)

08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at java.lang.reflect.Method.invoke(Method.java:498) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at java.lang.reflect.Method.invoke(Method.java:498) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at seraphaestus.historicizedmedicine.HMedicineMod.preInit(HMedicineMod.java:36) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at seraphaestus.historicizedmedicine.ServerProxy.preInit(ServerProxy.java:14) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at seraphaestus.historicizedmedicine.CommonProxy.preInit(CommonProxy.java:87) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at seraphaestus.historicizedmedicine.CraftingTable.Recipe.getFromJson(Recipe.java:87) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_180713_a(SourceFile:29) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_193609_a(SourceFile:34) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:190) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_193610_d(SourceFile:160) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_193593_f(SourceFile:185) 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: at net.minecraft.nbt.JsonToNBT.func_193602_b(SourceFile:61) 08.07 02:59:25 [Server] INFO "top3": {<--[HERE] 08.07 02:59:25 [Server] INFO }, 08.07 02:59:25 [Server] INFO "amount": 1 08.07 02:59:25 [Server] Server thread/INFO [STDERR]: [seraphaestus.historicizedmedicine.CraftingTable.Recipe:getFromJson:100]: net.minecraft.nbt.NBTException: Expected non-empty key at: ...nd",
